### ISSUE TITLE
Waiting for the contrastive learning code

### ISSUE THREAD

**Issue by Mollylulu** [laura-wang/video-pace#11]

**Comment by laura-wang** [comment]
Thanks for your interest.  Sorry, I am quite busy these days, working some new topics. I will release the code as soon as possible (hoefully)...

If you are in a hurry to use the contrastive learning code for video,  facebook has conducted a large-dcale study "A Large-Scale Study on Unsupervised Spatiotemporal Representation Learning"
,  and the code is releasedat https://github.com/facebookresearch/SlowFast, please first refer to this code.

**Comment by Mollylulu** [comment]
> Thanks for your interest. Sorry, I am quite busy these days, working some new topics. I will release the code as soon as possible (hoefully)...
> 
> If you are in a hurry to use the contrastive learning code for video, facebook has conducted a large-dcale study "A Large-Scale Study on Unsupervised Spatiotemporal Representation Learning"
> , and the code is releasedat https://github.com/facebookresearch/SlowFast, please first refer to this code.

thank you and waiting for your code as well :)
