### ISSUE TITLE
error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

### ISSUE THREAD

**Issue by loovi7** [laura-wang/video-pace#14]
I got the error like this 
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-6sxsq0tp\opencv\modules\imgproc\src\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
and I dont know how to address it, could you help me?

**Comment by RajArPatra** [comment]
@loovi7 This is because there is a mismatch in the file path of the dataset class change it according to your dataset format and you are good to go.

**Comment by wjun0830** [comment]
Can you provide any instructions about how to go through this issue?
