### ISSUE TITLE
How to preprocess data? 

### ISSUE THREAD

**Issue by shamanez** [laura-wang/video-pace#3]
I want to try this with a custom video dataset. How can I do it? I have the following questions.

1. What should be the maximum length of a single training video clip?
       - Is it similar to the UCF101 dataset or we can use longer videos? 
2. Should each video be saved as image frames? 
3. What is the framerate?

**Comment by laura-wang** [comment]
Sorry for the late reply.  Hope you still need the answers.

1. The maximum length of single video clip is not limited to 16. These days, many other researchers also use 32 or 64 frames. It depends on your GPU memory. Normally, the longer the video, the better the performance. 
2.  It is ok to first extract the video to frames (I normally do this). But there are other libraries that can load video data directly.
3.  The framerate I used is the standard 25 fps.
