### ISSUE TITLE
Can you release your code about contrast learning?

### ISSUE THREAD

**Issue by huangjinghuangjing** [laura-wang/video-pace#4]
When reading your code, I found that there seems to be a lack of code for contrast learning！

**Comment by baoxin1100** [comment]
I found nothing about contrast learning yet!

**Comment by laura-wang** [comment]
Thanks for your interest.  Sorry, I am quite busy these days...
The contrastive learning we used is similar as the SimCLR framewrok. I believe it is not difficult to implement by yourself. 
I will clean and release the code when I am not so busy....Please stay tuned.

**Comment by RajArPatra** [comment]
@laura-wang  any updates on the contrastive learning code?

**Comment by laura-wang** [comment]
Thanks for your interest. Sorry, I am quite busy these days, working some new topics. I will release the code as soon as possible (hopefully)...

If you are in a hurry to use the contrastive learning code for video, facebook has conducted a large-dcale study "A Large-Scale Study on Unsupervised Spatiotemporal Representation Learning"
, and the code is releasedat https://github.com/facebookresearch/SlowFast, please first refer to this code.
