### ISSUE TITLE
Contrast learning

### ISSUE THREAD

**Issue by Tramac** [laura-wang/video-pace#6]
Clean code! Looking forward to the code for contrast learning

**Comment by laura-wang** [comment]
Thanks for your interest.  Sorry, I am quite busy these days, working some new topics. I will release the code as soon as possible (hoefully)...

If you are in a hurry to use the contrastive learning code for video,  facebook has conducted a large-dcale study "A Large-Scale Study on Unsupervised Spatiotemporal Representation Learning"
,  and the code is releasedat https://github.com/facebookresearch/SlowFast, please first refer to this code.
